spring:

  # 数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: gjz147258

  # jpa
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

# 日志
logging:
  level:
    root: warn
    com.gjz: info
  file:
    name: log/blog-pro.log
  #    path: log/blog.log
  logback:
    rollingpolicy:
      max-file-size: 4MB
      file-name-pattern: log/blog-pro.%d{yyyy-MM-dd}.%i.log
      max-history: 30


